services:
  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml
    restart: always
    network_mode: "host"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml

  backend:
    build:
      context: ../livebackend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    environment:
      - LIVEKIT_API_KEY=devkey_12345678901234567890123456789012
      - LIVEKIT_API_SECRET=devsecret_123456789012345678901234567890123456789012345678901234567890
      - LIVEKIT_URL=ws://194.163.187.104:7880
      - PORT=5000
